### ISSUE TITLE
How to read the causal-label?

### ISSUE THREAD

**Issue by zhuchichi56** [google-research/causal-agents#2]
**Issue Description:**

Hi, thanks for your amazing work! I'm encountering an issue while parsing TFRecord files using TensorFlow. I'm unable to parse the data within them, and I'm getting the following error message:

**Error Message:**

2023-09-08 15:07:54.635147: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at example_parsing_ops.cc:94: INVALID_ARGUMENT: Could not parse example input, value: '
...
InvalidArgumentError: {{function_node __wrapped__ParseExampleV2_Tdense_0_num_sparse_2_ragged_split_types_0_ragged_value_types_0_sparse_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Could not parse example input, value: '

**Specifications:**

- TensorFlow Version: 2.0.0
- Operating System: Ubuntu 20.04

**Background:**

I'm encountering an issue while attempting to parse TFRecord files using TensorFlow. The error message suggests a problem with parsing the example input. 

**Issue Details:**

I've defined the dataset description, including variable-length features (VarLenFeature), but it seems there's an issue during parsing. Here's a code snippet:

```python
filename = "causal_labels.tfrecord"
dataset = tf.data.TFRecordDataset(filename, compression_type='')
data = next(dataset.as_numpy_iterator())

features_description = {}
causal_features = {
    'scenario_id': tf.io.VarLenFeature(tf.string),
    'labeler_results': tf.io.VarLenFeature(tf.string),
}

features_description.update(causal_features)
parsed = tf.io.parse_single_example(data, features_description)
```

**Expected Outcome:**

I hope to successfully parse the data within the TFRecord file for further data processing and analysis.

Please help me identify the cause of the parsing issue and how to resolve it. Thank you for your assistance!

**Comment by zhuchichi56** [comment]
Great , I have solved this problem.

**Comment by yhli123** [comment]
Hi! Could you please give me some ideas on how you solved the problem? I am encountering the same problem.

**Comment by yhli123** [comment]
I resolved this by using the proto file. Thanks.

**Comment by kangmiao15** [comment]
I also encountered the same problem. How did you solve it in the end? Could you share the code?
